### PR TITLE
Add .luacheckrc and do some style-related changes

### PR DESCRIPTION
**Pull request by HybridDog**
With luacheck mistakes in lua code can be found, e.g. the use of undefined variables, and the code style can be checked.
I've added a .luacheckrc for WorldEdit, removed trailing whitespace and whitespace before tabs, and removed or renamed unused variables.

I've also changed something in compatibility.lua which was probably wrong:
```
Checking worldedit/compatibility.lua              2 warnings

    worldedit/compatibility.lua:27:40: value of argument filename is overwritten on line 29 before use
    worldedit/compatibility.lua:29:55: accessing undefined variable file
```

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Would be nice if you could add a GitHub workflow like in #189, so we can easily know if there are errors/warnings. 🙂

**Comment by HybridDog** [comment]
Thanks. I added your workflow.
I didn't add the Readme badge because I think it's useless.

**Review by BuckarooBanzay — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
LGTM.

**Review by wsor4035 — APPROVED** [review]

**Comment by Panquesito7** [comment]
Ping.

**Comment by sfan5** [comment]
I don't agree with some of the style changes.
Can you split this so we add the workflow first in a separate PR?

**Comment by HybridDog** [comment]
> Can you split this so we add the workflow first in a separate PR?

Yes, splitting it is a good idea.

**Comment by sfan5** [comment]
Thanks

**Pull request closed without merging**
